version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing Terraform...
      - curl -O https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_arm64.zip
      - unzip terraform_1.6.0_linux_arm64.zip
      - mv terraform /usr/local/bin/

  pre_build:
    commands:
      - echo Logging into AWS...
      - terraform --version
      - terraform init
      - docker --version 
  build:
    commands:
      - echo Provisioning EC2...
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
